apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-api-deployment
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: api
        image: ksksrikanth/7am-lms-be
        ports:
        - containerPort: 8080
