pipeline {
    agent {
        label 'eks'
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockeruser')
        registry = "ksksrikanth"
        registryCredential = 'dockeruser'
        dockerImage = ''
    }
    stages {
      
        stage('docker login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
      
        stage('running backend container') {
            steps {
                sh 'kubectl apply -f frontend-deployment.yml'
                sh 'kubectl apply -f frontend-svc.yml'
            }
        }
    }    
}
