apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-frontend-deployment
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: ksksrikanth/frontend-lms
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value:"http://ac530acef547a4773835a103acfc8a4d-1603901027.ca-central-1.elb.amazonaws.com:8080/api"
