apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-frontend-deployment
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: ksksrikanth/7am-lms-fe
        ports:
        - containerPort: 80
        -name=VITE_API_URL
        value=6666:8080/api
